name: Synthesine

collections:
  examples:
    output: true
  reference:
    output: true

example-categories: [oscillator, envelope, modulation, filter, synthesis, instrument]
reference-categories: [object, variables, manipulation, oscillator, filter]


baseurl: /synthesine